---
title: "knnwr, knnwda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{knnwr, knnwda}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}

knitr::opts_chunk$set(echo = TRUE) 

```

```{r, message = FALSE, warning = FALSE}

library(rnirs)             
library(ggplot2)

```

```{r}

data(datcass)
data(datforages)

```

## knnwr

```{r, fig.width = 7, fig.height = 3}

Xr <- datcass$Xr
yr <- datcass$yr

Xu <- datcass$Xu
yu <- datcass$yu

Xr <- savgol(snv(Xr), n = 21, p = 2, m = 2)
Xu <- savgol(snv(Xu), n = 21, p = 2, m = 2)
dim(Xr)
dim(Xu)

## A kNN-WR model where:
## The dissimilarities between the observations are defined
## by the Mahalanobis distances calculated from a global PLS score space
## of ncompdis = 10 components.
## - Weighting 1 = knn selection of k = {5, 10, 15} neighbors
## - Weighting 2 = within each neighborhood, weights are calculated by "wkern" 

ncompdis <- 10
h <- c(1, 2)
k <- seq(5, 20, by = 5)
fm <- knnwr(
  Xr, yr,
  Xu, yu,
  ncompdis = ncompdis, diss = "mahalanobis",
  h = h, k = k,
  print = TRUE
  )
names(fm)
head(fm$y)
head(fm$fit)
head(fm$r)
z <- mse(fm, ~ ncompdis + h + k)
z
z[z$rmsep == min(z$rmsep), ]

u <- z
u$group <- paste(u$ncompdis, u$h)
p <- ggplot(data = u, aes(x = k, y = rmsep))
p <- p + geom_point(aes(colour = as.factor(group)), size = 2)
p

## Same but where :
## The dissimilarities between the observations are defined
## by Euclidean distances calculated from the original (i.e. not compressed) X data

ncompdis <- NULL
h <- c(1, 2)
k <- seq(5, 20, by = 5)
fm <- knnwr(
  Xr, yr,
  Xu, yu,
  ncompdis = ncompdis, diss = "euclidean",
  h = h, k = k,
  print = TRUE
  )
z <- mse(fm, ~ ncompdis + h + k)
z
z[z$rmsep == min(z$rmsep), ]
u <- z

u$group <- paste(u$ncompdis, u$h)
p <- ggplot(data = u, aes(x = k, y = rmsep))
p <- p + geom_point(aes(colour = as.factor(group)), size = 2)
p

```

## knnwda

```{r, fig.width = 7, fig.height = 3}

Xr <- datforages$Xr
yr <- datforages$yr

Xu <- datforages$Xu
yu <- datforages$yu

Xr <- savgol(snv(Xr), n = 21, p = 2, m = 2)
Xu <- savgol(snv(Xu), n = 21, p = 2, m = 2)
dim(Xr)
dim(Xu)

table(yr)
table(yu)

## A kNNWDA model where:
## The dissimilarities between the observations are defined
## by the Mahalanobis distances calculated from a global PLS score space
## of ncompdis = 10 components.
## - Weighting 1 = knn selection of k = {5, 10, 15} neighbors
## - Weighting 2 = within each neighborhood, weights are calculated by "wkern" 

ncompdis <- 10
h <- c(1, 2)
k <- seq(5, 15, by = 5)
fm <- knnwda(
  Xr, yr,
  Xu, yu,
  ncompdis = ncompdis, diss = "mahalanobis",
  h = h, k = k,
  print = TRUE
  )
names(fm)
head(fm$y)
head(fm$fit)
head(fm$r)
z <- err(fm, ~ ncompdis + h + k)
z
z[z$err == min(z$errp), ]

u <- z
u$group <- paste(u$ncompdis, u$h)
p <- ggplot(data = u, aes(x = k, y = errp))
p <- p + geom_point(aes(colour = as.factor(group)), size = 2)
p

```
